# golangci-lint configuration for General Purpose Chatbot Framework
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lewisedginton/general-purpose-chatbot
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: UK
  lll:
    line-length: 120
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "Use os or io package instead"
  revive:
    severity: warning
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
      - name: function-result-limit
        arguments: [3]
      - name: cognitive-complexity
        arguments: [20]

linters:
  enable:
    # Base linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional quality linters
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - goconst
    - misspell
    - revive
    - gosec
    - lll
    - depguard
    
    # Performance and best practices
    - prealloc
    - unconvert
    - unparam
    - gocognit
    - gocritic
    - contextcheck
    - bodyclose
    - noctx
    
  disable:
    # Disable noisy linters for now
    - exhaustive
    - exhaustruct
    - funlen
    - cyclop
    - wsl
    - nlreturn
    - varnamelen
    - tagliatelle

  # Don't enable these by default but consider for strict mode:
  # - dupl
  # - goconst
  # - gomnd