# golangci-lint configuration for General Purpose Chatbot Framework
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/lewisedginton/general-purpose-chatbot
    gofumpt:
      extra-rules: true

linters:
  enable:
    # Base linters (gosimple merged into staticcheck as of v2)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - gocyclo
    - goconst
    - misspell
    - revive
    - gosec
    - lll
    - depguard

    # Performance and best practices
    - prealloc
    - unconvert
    - unparam
    - gocognit
    - gocritic
    - contextcheck
    - bodyclose
    - noctx

  disable:
    # Disable noisy linters for now
    - exhaustive
    - exhaustruct
    - funlen
    - cyclop
    - wsl
    - nlreturn
    - varnamelen
    - tagliatelle

  settings:
    govet:
      check-shadowing: true
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: UK
    lll:
      line-length: 120
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Use os or io package instead"
    revive:
      severity: warning
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: function-result-limit
          arguments: [3]
        - name: cognitive-complexity
          arguments: [20]

  # Don't enable these by default but consider for strict mode:
  # - dupl
  # - goconst
  # - gomnd
