# golangci-lint v2 configuration for General Purpose Chatbot Framework
version: "2"

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      print-linter-name: true

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

linters:
  default: none
  enable:
    # Base linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - gocyclo
    - goconst
    - misspell
    - revive
    - gosec
    - lll
    - depguard

    # Performance and best practices
    - prealloc
    - unconvert
    - unparam
    - gocognit
    - gocritic
    - contextcheck
    - bodyclose
    - noctx

  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: UK
    lll:
      line-length: 150
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Use os or io package instead"
    revive:
      severity: warning
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: package-comments
        - name: var-naming
        - name: function-result-limit
          arguments: [3]
        - name: cognitive-complexity
          arguments: [20]

  exclusions:
    generated: lax
    paths:
      - internal/cli/persistence/sqlc
    rules:
      # Exclude complexity checks for test files
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - unparam
          - prealloc
          - gocyclo
          - gocognit
          - revive
          - noctx
          - goconst
      # Exclude var-naming for packages with underscores (convention choice)
      - path: pkg/prefixed_uuid/
        linters:
          - revive
        text: "var-naming"
      - path: internal/tools/agent_info/
        linters:
          - revive
        text: "var-naming"
      - path: internal/tools/http_request/
        linters:
          - revive
        text: "var-naming"
      - path: internal/tools/lua_script/
        linters:
          - revive
        text: "var-naming"
      - path: internal/session_manager/
        linters:
          - revive
        text: "var-naming"
      - path: internal/storage_manager/
        linters:
          - revive
        text: "var-naming"
      - path: internal/skills_manager/
        linters:
          - revive
        text: "var-naming"
      - path: internal/prompt_manager/
        linters:
          - revive
        text: "var-naming"
      # Exclude contextcheck for manager creation (context not needed at init)
      - path: internal/server/server\.go
        linters:
          - contextcheck
      # Exclude high complexity for config validation (necessary complexity)
      - path: pkg/config/config\.go
        linters:
          - gocognit
          - gocyclo
          - revive
      - path: internal/config/config\.go
        linters:
          - gocognit
          - gocyclo
          - revive
      # Exclude complexity for transform functions (necessary for protocol conversion)
      - path: internal/models/anthropic/transform\.go
        linters:
          - gocognit
          - gocyclo
          - revive
          - unparam
      - path: internal/models/openai/transform\.go
        linters:
          - gocognit
          - gocyclo
          - revive
          - unparam
      # Exclude complexity for model implementations
      - path: internal/models/anthropic/claude\.go
        linters:
          - gocyclo
          - revive
      - path: internal/models/openai/openai\.go
        linters:
          - gocyclo
          - revive
      # Exclude complexity for session service (necessary for persistence logic)
      - path: internal/session_manager/session_service\.go
        linters:
          - gocyclo
          - revive
      # Exclude complexity for executor
      - path: internal/connectors/executor/executor\.go
        linters:
          - gocyclo
          - revive
      # Exclude complexity for agent factory
      - path: internal/agents/agent\.go
        linters:
          - revive
      # Exclude complexity for server run
      - path: internal/server/server\.go
        linters:
          - revive
      # Exclude function-result-limit for grpc helpers (existing API)
      - path: pkg/utils/grpc_helpers\.go
        linters:
          - revive
        text: "function-result-limit"
