# golangci-lint configuration for General Purpose Chatbot Framework
# Based on official v2 schema: https://golangci-lint.run/docs/configuration/file/
version: "2"

run:
  timeout: 5m
  tests: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/lewisedginton/general-purpose-chatbot

linters:
  enable:
    # Base linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - gocyclo
    - goconst
    - misspell
    - revive
    - gosec
    - lll
    - depguard

    # Performance and best practices
    - prealloc
    - unconvert
    - unparam
    - gocognit
    - gocritic
    - contextcheck
    - bodyclose
    - noctx

  disable:
    - exhaustive
    - exhaustruct
    - funlen
    - cyclop
    - wsl
    - nlreturn
    - varnamelen
    - tagliatelle

  exclusions:
    # Exclude sqlc-generated files and tests
    paths:
      - "internal/cli/persistence/sqlc"
      - ".*_test\\.go$"

  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: UK
    lll:
      line-length: 150
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Use os or io package instead"
    revive:
      severity: warning
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck  # Allow types like health.HealthChecker
        - name: package-comments
        - name: var-naming
        - name: function-result-limit
          arguments: [3]
        - name: cognitive-complexity
          arguments: [20]
