# golangci-lint v2 configuration for General Purpose Chatbot Framework
version: "2"

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      print-linter-name: true

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

linters:
  default: none
  enable:
    # Base linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - gocyclo
    - goconst
    - misspell
    - revive
    - gosec
    - lll
    - depguard

    # Performance and best practices
    - prealloc
    - unconvert
    - unparam
    - gocognit
    - gocritic
    - contextcheck
    - bodyclose
    - noctx

  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    lll:
      line-length: 150
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Use os or io package instead"
    revive:
      severity: warning
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: package-comments
        - name: var-naming
        - name: function-result-limit
          arguments: [3]
        - name: cognitive-complexity
          arguments: [20]

  exclusions:
    generated: lax
    paths:
      - internal/cli/persistence/sqlc
    rules:
      # Exclude some checks for test files (standard practice)
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - unparam
          - prealloc
          - gocyclo
          - gocognit
          - revive
          - noctx
          - goconst
          - staticcheck
