// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FileProvider is an autogenerated mock type for the FileProvider type
type FileProvider struct {
	mock.Mock
}

type FileProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FileProvider) EXPECT() *FileProvider_Expecter {
	return &FileProvider_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, path
func (_m *FileProvider) Delete(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FileProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *FileProvider_Expecter) Delete(ctx interface{}, path interface{}) *FileProvider_Delete_Call {
	return &FileProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *FileProvider_Delete_Call) Run(run func(ctx context.Context, path string)) *FileProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileProvider_Delete_Call) Return(_a0 error) *FileProvider_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileProvider_Delete_Call) RunAndReturn(run func(context.Context, string) error) *FileProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, path
func (_m *FileProvider) Exists(ctx context.Context, path string) (bool, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type FileProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *FileProvider_Expecter) Exists(ctx interface{}, path interface{}) *FileProvider_Exists_Call {
	return &FileProvider_Exists_Call{Call: _e.mock.On("Exists", ctx, path)}
}

func (_c *FileProvider_Exists_Call) Run(run func(ctx context.Context, path string)) *FileProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileProvider_Exists_Call) Return(_a0 bool, _a1 error) *FileProvider_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileProvider_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *FileProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, prefix
func (_m *FileProvider) List(ctx context.Context, prefix string) ([]string, error) {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileProvider_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FileProvider_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *FileProvider_Expecter) List(ctx interface{}, prefix interface{}) *FileProvider_List_Call {
	return &FileProvider_List_Call{Call: _e.mock.On("List", ctx, prefix)}
}

func (_c *FileProvider_List_Call) Run(run func(ctx context.Context, prefix string)) *FileProvider_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileProvider_List_Call) Return(_a0 []string, _a1 error) *FileProvider_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileProvider_List_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *FileProvider_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, path
func (_m *FileProvider) Read(ctx context.Context, path string) ([]byte, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileProvider_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type FileProvider_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *FileProvider_Expecter) Read(ctx interface{}, path interface{}) *FileProvider_Read_Call {
	return &FileProvider_Read_Call{Call: _e.mock.On("Read", ctx, path)}
}

func (_c *FileProvider_Read_Call) Run(run func(ctx context.Context, path string)) *FileProvider_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileProvider_Read_Call) Return(_a0 []byte, _a1 error) *FileProvider_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileProvider_Read_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *FileProvider_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: ctx, path, data
func (_m *FileProvider) Write(ctx context.Context, path string, data []byte) error {
	ret := _m.Called(ctx, path, data)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileProvider_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type FileProvider_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data []byte
func (_e *FileProvider_Expecter) Write(ctx interface{}, path interface{}, data interface{}) *FileProvider_Write_Call {
	return &FileProvider_Write_Call{Call: _e.mock.On("Write", ctx, path, data)}
}

func (_c *FileProvider_Write_Call) Run(run func(ctx context.Context, path string, data []byte)) *FileProvider_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *FileProvider_Write_Call) Return(_a0 error) *FileProvider_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileProvider_Write_Call) RunAndReturn(run func(context.Context, string, []byte) error) *FileProvider_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileProvider creates a new instance of FileProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileProvider {
	mock := &FileProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
